workflows:
  build-nekogram-android:
    name: Build Nekogram Android
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build APK & AAB from TMessagesProj
        script: |
          ./gradlew :TMessagesProj:assembleRelease :TMessagesProj:bundleRelease
    artifacts:
      - TMessagesProj/build/outputs/**/*.apk
      - TMessagesProj/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - rgebhfbgt@gmail.com
        notify:
          success: true
          failure: true
