workflows:
  build-nekogram-android:
    name: Build Nekogram Android APK
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build release APK for TMessagesProj_App
        script: |
          ./gradlew :TMessagesProj_App:assembleRelease
    artifacts:
      - TMessagesProj_App/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rgebhfbgt@gmail.com
        notify:
          success: true
          failure: true
