workflows:
  build-nekogram-android:
    name: Build Nekogram Android
    max_build_duration: 120
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "main.nekogram.mktdaa"  # غيّره إن كان مختلف
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build release APK & AAB
        script: |
          ./gradlew assembleRelease bundleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - rgebhfbgt@gmail.com
        notify:
          success: true
          failure: true
    tools:
      android_sdk: "34"
